//! OID4VP 1.0 Final Conformance Tests — Marty Verifier (Tauri app layer).
//!
//! These tests exercise the verifier's own JSON wire format: the
//! `credential_data` JSON object accepted by the `verify_credential` Tauri
//! command.  They complement the engine-level tests in
//! `marty-core/marty-oid4vci/tests/oid4vp_conformance.rs` by adding coverage
//! of the JSON parsing + `VerificationResult` construction layers that live
//! exclusively in this crate.
//!
//! Mock: no Tauri runtime, no `AppState`.  Tests call
//! `marty_verifier::commands::verification::verify_oid4vp_offline` which
//! mirrors the offline path of `verify_oid4vp_payload` without the liveness-
//! check, license-check, and storage plumbing.
//!
//! Shared fixture corpus: same files generated by
//! `marty-integration-tests/tests/integration/fixtures/conformance/generate_fixtures.py`
//! and consumed by the Python and Rust engine suites.
//!
//! Key constants (must match the generate_fixtures.py values):
//!   VERIFIER_ID = "https://verifier.example.com"
//!   NONCE       = "n-0S6_WzA2Mj"
//!   (static VP token has aud = VERIFIER_ID, nonce = NONCE, exp = 9999999999)

#![cfg(feature = "oid4vp")]

use marty_verifier::commands::verification::{verify_oid4vp_offline, VerificationStatus};

// ── Shared fixture corpus ─────────────────────────────────────────────────────

const VERIFIER_ID: &str = "https://verifier.example.com";
const NONCE: &str = "n-0S6_WzA2Mj";

const STATIC_VP_TOKEN: &str = include_str!(
    "../../../marty-integration-tests/tests/integration/fixtures/conformance/vp_token_jwt.txt"
);
const PRESENTATION_DEFINITION_JSON: &str = include_str!(
    "../../../marty-integration-tests/tests/integration/fixtures/conformance/presentation_definition.json"
);
const PRESENTATION_SUBMISSION_JSON: &str = include_str!(
    "../../../marty-integration-tests/tests/integration/fixtures/conformance/presentation_submission.json"
);

/// Build a `credential_data` JSON string in the format `verify_credential` accepts.
fn credential_data(vp_token: &str, nonce: &str) -> String {
    serde_json::json!({
        "vp_token": vp_token.trim(),
        "nonce": nonce,
    })
    .to_string()
}

fn credential_data_with_pd(vp_token: &str, nonce: &str, pd: &str, ps: &str) -> String {
    serde_json::json!({
        "vp_token": vp_token.trim(),
        "nonce": nonce,
        "presentation_definition": serde_json::from_str::<serde_json::Value>(pd).unwrap(),
        "presentation_submission": serde_json::from_str::<serde_json::Value>(ps).unwrap(),
    })
    .to_string()
}

// ── §1  JSON Parsing (verifier wire format) ──────────────────────────────────

/// `verify_credential` must return an error when `vp_token` is absent from the
/// `credential_data` JSON object.
#[test]
fn missing_vp_token_field_returns_error() {
    let data = r#"{"nonce":"n-0S6_WzA2Mj"}"#;
    let result = verify_oid4vp_offline(data, VERIFIER_ID, VERIFIER_ID);
    assert!(
        result.is_err(),
        "Expected Err when vp_token field is missing, got {:?}",
        result
    );
    let msg = result.unwrap_err().to_string();
    assert!(
        msg.contains("vp_token"),
        "Error should mention 'vp_token', got: {msg}"
    );
}

/// Non-JSON `credential_data` must be rejected immediately.
#[test]
fn credential_data_not_json_returns_error() {
    let result = verify_oid4vp_offline("not valid json", VERIFIER_ID, VERIFIER_ID);
    assert!(result.is_err(), "Expected Err for non-JSON input");
}

/// An empty JSON object (no `vp_token`) must produce a clear error.
#[test]
fn empty_json_object_returns_error() {
    let result = verify_oid4vp_offline("{}", VERIFIER_ID, VERIFIER_ID);
    assert!(result.is_err());
}

// ── §2  Happy Path ────────────────────────────────────────────────────────────

/// Core conformance test: the static fixture VP token (signed with the shared
/// Ed25519 seed, correct `aud` + `nonce` + far-future `exp`) must verify as
/// `Valid` through the offline path.
#[test]
fn happy_path_offline_flow_returns_valid_status() {
    let data = credential_data(STATIC_VP_TOKEN, NONCE);
    let result = verify_oid4vp_offline(&data, VERIFIER_ID, VERIFIER_ID)
        .expect("verify_oid4vp_offline should not error on valid input");
    assert_eq!(
        result.status,
        VerificationStatus::Valid,
        "Happy-path VP token must verify as Valid; warnings: {:?}",
        result.warnings
    );
}

/// The offline verification path MUST include an offline disclaimer warning
/// (OID4VP §11: revocation checking requires connectivity).
#[test]
fn offline_result_contains_offline_warning() {
    let data = credential_data(STATIC_VP_TOKEN, NONCE);
    let result = verify_oid4vp_offline(&data, VERIFIER_ID, VERIFIER_ID).unwrap();
    assert!(
        result.warnings.iter().any(|w| w.contains("offline")),
        "Offline result MUST contain an offline-mode warning; got: {:?}",
        result.warnings
    );
}

/// `trust_chain.chain_type` must be "oid4vp" for OID4VP credentials.
#[test]
fn offline_result_trust_chain_type_is_oid4vp() {
    let data = credential_data(STATIC_VP_TOKEN, NONCE);
    let result = verify_oid4vp_offline(&data, VERIFIER_ID, VERIFIER_ID).unwrap();
    assert_eq!(
        result.trust_chain.chain_type, "oid4vp",
        "trust_chain.chain_type must be 'oid4vp'"
    );
}

/// `trust_chain.offline_verified` must be `true` in the offline path.
#[test]
fn offline_result_reports_offline_verified_true() {
    let data = credential_data(STATIC_VP_TOKEN, NONCE);
    let result = verify_oid4vp_offline(&data, VERIFIER_ID, VERIFIER_ID).unwrap();
    assert!(
        result.trust_chain.offline_verified,
        "trust_chain.offline_verified must be true for offline verification"
    );
}

/// `credential_type` in the result must be "oid4vp".
#[test]
fn offline_result_credential_type_is_oid4vp() {
    let data = credential_data(STATIC_VP_TOKEN, NONCE);
    let result = verify_oid4vp_offline(&data, VERIFIER_ID, VERIFIER_ID).unwrap();
    assert_eq!(result.credential_type, "oid4vp");
}

/// `verification_id` must be a non-empty UUID string.
#[test]
fn offline_result_verification_id_is_non_empty() {
    let data = credential_data(STATIC_VP_TOKEN, NONCE);
    let result = verify_oid4vp_offline(&data, VERIFIER_ID, VERIFIER_ID).unwrap();
    assert!(!result.verification_id.is_empty());
    // Rough UUID format: 8-4-4-4-12 hex digits
    assert_eq!(
        result.verification_id.len(),
        36,
        "Expect UUID format (36 chars)"
    );
}

// ── §3  Rejection Cases ───────────────────────────────────────────────────────

/// OID4VP §6: VP token with wrong nonce must be rejected.
/// The nonce "wrong-nonce" does not match the fixture token's embedded nonce.
#[test]
fn wrong_nonce_in_credential_data_returns_invalid() {
    let data = credential_data(STATIC_VP_TOKEN, "wrong-nonce-value");
    let result = verify_oid4vp_offline(&data, VERIFIER_ID, VERIFIER_ID)
        .expect("Wrong nonce should still parse; engine should return Invalid");
    assert_eq!(
        result.status,
        VerificationStatus::Invalid,
        "Nonce mismatch MUST produce Invalid; warnings: {:?}",
        result.warnings
    );
}

/// OID4VP §5: VP token presented to the wrong verifier (`aud` mismatch) must
/// be rejected. Passing a different `verifier_id` simulates this.
#[test]
fn wrong_verifier_id_audience_mismatch_returns_invalid() {
    let data = credential_data(STATIC_VP_TOKEN, NONCE);
    let result = verify_oid4vp_offline(
        &data,
        "https://wrong.verifier.example.com",
        "https://wrong.verifier.example.com",
    )
    .expect("Audience mismatch should still parse; engine should return Invalid");
    assert_eq!(
        result.status,
        VerificationStatus::Invalid,
        "Audience (verifier_id) mismatch MUST produce Invalid"
    );
}

/// A completely malformed JWT (random three-segment string with no valid
/// crypto) must produce `Invalid`.
#[test]
fn malformed_vp_token_returns_invalid() {
    let data = credential_data("abc.def.ghi", NONCE);
    let result = verify_oid4vp_offline(&data, VERIFIER_ID, VERIFIER_ID)
        .expect("Malformed JWT should still parse; engine should return Invalid");
    assert_eq!(result.status, VerificationStatus::Invalid);
}

/// An empty VP token string must produce `Invalid`.
#[test]
fn empty_vp_token_returns_invalid() {
    let data = credential_data("", NONCE);
    let result = verify_oid4vp_offline(&data, VERIFIER_ID, VERIFIER_ID)
        .expect("Empty VP token should still parse; engine should return Invalid");
    assert_eq!(result.status, VerificationStatus::Invalid);
}

/// A single-segment JWT (not a JWT at all) must produce `Invalid`.
#[test]
fn single_segment_not_jwt_returns_invalid() {
    let data = credential_data("notajwt", NONCE);
    let result = verify_oid4vp_offline(&data, VERIFIER_ID, VERIFIER_ID)
        .expect("Single-segment input should still parse; engine should return Invalid");
    assert_eq!(result.status, VerificationStatus::Invalid);
}

// ── §4  Presentation Definition + Submission (structural check) ──────────────

/// When both `presentation_definition` and `presentation_submission` are
/// present in the payload and match each other, the result must remain
/// `Valid` (structural check passes).
#[test]
fn with_matching_pd_and_ps_result_is_valid() {
    let data = credential_data_with_pd(
        STATIC_VP_TOKEN,
        NONCE,
        PRESENTATION_DEFINITION_JSON,
        PRESENTATION_SUBMISSION_JSON,
    );
    let result = verify_oid4vp_offline(&data, VERIFIER_ID, VERIFIER_ID)
        .expect("PD+PS structural check should not error");
    assert_eq!(
        result.status,
        VerificationStatus::Valid,
        "Matching PD+PS must still produce Valid; warnings: {:?}",
        result.warnings
    );
}

/// Without PD/PS fields the structural check is skipped; result is still Valid.
#[test]
fn without_pd_and_ps_structural_check_is_skipped() {
    let data = credential_data(STATIC_VP_TOKEN, NONCE);
    let result = verify_oid4vp_offline(&data, VERIFIER_ID, VERIFIER_ID).unwrap();
    assert_eq!(result.status, VerificationStatus::Valid);
}

/// A `presentation_submission` whose `definition_id` does not match the
/// `presentation_definition.id` MUST cause the structural check to fail,
/// producing `Invalid` status.  (DIF PE v2 §5 + OID4VP §5.2.)
#[test]
fn mismatched_ps_definition_id_produces_invalid() {
    // Patch the submission's definition_id to something wrong
    let mut ps: serde_json::Value = serde_json::from_str(PRESENTATION_SUBMISSION_JSON).unwrap();
    ps["definition_id"] = serde_json::json!("wrong-definition-id");

    let data = serde_json::json!({
        "vp_token": STATIC_VP_TOKEN.trim(),
        "nonce": NONCE,
        "presentation_definition": serde_json::from_str::<serde_json::Value>(PRESENTATION_DEFINITION_JSON).unwrap(),
        "presentation_submission": ps,
    })
    .to_string();

    let result = verify_oid4vp_offline(&data, VERIFIER_ID, VERIFIER_ID)
        .expect("Mismatched definition_id should still parse");

    assert_eq!(
        result.status,
        VerificationStatus::Invalid,
        "Mismatched PD definition_id MUST produce Invalid status; warnings: {:?}",
        result.warnings
    );
}

// ── §6  PEX Field Constraint Evaluation (DIF PE v2 §5) ───────────────────────

/// Build a `credential_data` JSON string with a custom presentation definition
/// and submission for PEX field constraint evaluation tests.
fn credential_data_with_custom_pd(
    vp_token: &str,
    nonce: &str,
    pd_json: &str,
    ps_json: &str,
) -> String {
    serde_json::json!({
        "vp_token": vp_token.trim(),
        "nonce": nonce,
        "presentation_definition": serde_json::from_str::<serde_json::Value>(pd_json).unwrap(),
        "presentation_submission": serde_json::from_str::<serde_json::Value>(ps_json).unwrap(),
    })
    .to_string()
}

/// The standard descriptor map used by PEX §6 tests.
/// Navigates from the JWT root through the VP to the first verifiable credential.
const PEX_TEST_PS: &str = r#"{
    "id": "ps-pex-test",
    "definition_id": "pd-pex-test",
    "descriptor_map": [{
        "id": "credential",
        "format": "jwt_vp",
        "path": "$",
        "path_nested": {
            "id": "credential",
            "format": "jwt_vc",
            "path": "$.vp.verifiableCredential[0]"
        }
    }]
}"#;

/// DIF PE v2 §5.1: When the VP's credential satisfies the field constraint
/// filter (type array contains "UniversityDegreeCredential"), the result MUST
/// be `Valid`.
#[test]
fn pex_field_constraint_satisfied_is_valid() {
    let pd = r#"{
        "id": "pd-pex-test",
        "input_descriptors": [{
            "id": "credential",
            "constraints": {
                "fields": [{
                    "path": ["$.type"],
                    "filter": {
                        "type": "array",
                        "contains": { "const": "UniversityDegreeCredential" }
                    }
                }]
            }
        }]
    }"#;

    let data = credential_data_with_custom_pd(STATIC_VP_TOKEN, NONCE, pd, PEX_TEST_PS);
    let result = verify_oid4vp_offline(&data, VERIFIER_ID, VERIFIER_ID)
        .expect("PEX field constraint test should not error");

    assert_eq!(
        result.status,
        VerificationStatus::Valid,
        "Satisfied field constraint MUST produce Valid; warnings: {:?}",
        result.warnings
    );
}

/// DIF PE v2 §5.1: When the VP's credential type does NOT satisfy the `filter`
/// (the credential has "UniversityDegreeCredential" but "MedicalCredential" is
/// required), the result MUST be `Invalid`.
#[test]
fn pex_field_filter_unsatisfied_produces_invalid() {
    let pd = r#"{
        "id": "pd-pex-test",
        "input_descriptors": [{
            "id": "credential",
            "constraints": {
                "fields": [{
                    "path": ["$.type"],
                    "filter": {
                        "type": "array",
                        "contains": { "const": "MedicalCredential" }
                    }
                }]
            }
        }]
    }"#;

    let data = credential_data_with_custom_pd(STATIC_VP_TOKEN, NONCE, pd, PEX_TEST_PS);
    let result = verify_oid4vp_offline(&data, VERIFIER_ID, VERIFIER_ID)
        .expect("Filter mismatch should still parse");

    assert_eq!(
        result.status,
        VerificationStatus::Invalid,
        "Unsatisfied field filter MUST produce Invalid; warnings: {:?}",
        result.warnings
    );
}

/// DIF PE v2 §5.1: A required field (`$.credentialSubject.passport_number`)
/// that does not exist in the VP credential MUST produce `Invalid`.
#[test]
fn pex_missing_required_field_produces_invalid() {
    let pd = r#"{
        "id": "pd-pex-test",
        "input_descriptors": [{
            "id": "credential",
            "constraints": {
                "fields": [{
                    "path": ["$.credentialSubject.passport_number"]
                }]
            }
        }]
    }"#;

    let data = credential_data_with_custom_pd(STATIC_VP_TOKEN, NONCE, pd, PEX_TEST_PS);
    let result = verify_oid4vp_offline(&data, VERIFIER_ID, VERIFIER_ID)
        .expect("Missing field should still parse");

    assert_eq!(
        result.status,
        VerificationStatus::Invalid,
        "Missing required field MUST produce Invalid; warnings: {:?}",
        result.warnings
    );
}

/// DIF PE v2 §5.1.1: An absent field marked `optional: true` MUST NOT cause
/// the result to be `Invalid`.
#[test]
fn pex_optional_field_absent_is_valid() {
    let pd = r#"{
        "id": "pd-pex-test",
        "input_descriptors": [{
            "id": "credential",
            "constraints": {
                "fields": [
                    { "path": ["$.credentialSubject.given_name"] },
                    { "path": ["$.credentialSubject.passport_number"], "optional": true }
                ]
            }
        }]
    }"#;

    let data = credential_data_with_custom_pd(STATIC_VP_TOKEN, NONCE, pd, PEX_TEST_PS);
    let result = verify_oid4vp_offline(&data, VERIFIER_ID, VERIFIER_ID)
        .expect("Optional absent field should not error");

    assert_eq!(
        result.status,
        VerificationStatus::Valid,
        "Absent optional field MUST NOT produce Invalid; warnings: {:?}",
        result.warnings
    );
}

/// DIF PE v2 §5.1.1: `constraints.limit_disclosure: "required"` with a
/// `jwt_vp` format (not SD-JWT) MUST be rejected since the format cannot
/// honour selective disclosure.
#[test]
fn pex_limit_disclosure_required_non_sdjwt_produces_invalid() {
    let pd = r#"{
        "id": "pd-pex-test",
        "input_descriptors": [{
            "id": "credential",
            "constraints": {
                "fields": [{ "path": ["$.credentialSubject.given_name"] }],
                "limit_disclosure": "required"
            }
        }]
    }"#;

    let data = credential_data_with_custom_pd(STATIC_VP_TOKEN, NONCE, pd, PEX_TEST_PS);
    let result = verify_oid4vp_offline(&data, VERIFIER_ID, VERIFIER_ID)
        .expect("limit_disclosure mismatch should still parse");

    assert_eq!(
        result.status,
        VerificationStatus::Invalid,
        "limit_disclosure:required with non-SD-JWT MUST produce Invalid; warnings: {:?}",
        result.warnings
    );
}

/// A multi-descriptor PD where both descriptors are satisfied by the VP MUST
/// produce `Valid`.
#[test]
fn pex_multi_descriptor_all_satisfied_is_valid() {
    let pd = r#"{
        "id": "pd-pex-test",
        "input_descriptors": [
            {
                "id": "credential",
                "constraints": {
                    "fields": [{ "path": ["$.credentialSubject.given_name"] }]
                }
            },
            {
                "id": "credential2",
                "constraints": {
                    "fields": [{ "path": ["$.credentialSubject.degree"] }]
                }
            }
        ]
    }"#;

    // Both descriptors map to the same credential (for simplicity in test fixtures)
    let ps = r#"{
        "id": "ps-pex-multi",
        "definition_id": "pd-pex-test",
        "descriptor_map": [
            {
                "id": "credential",
                "format": "jwt_vp",
                "path": "$",
                "path_nested": {
                    "id": "credential",
                    "format": "jwt_vc",
                    "path": "$.vp.verifiableCredential[0]"
                }
            },
            {
                "id": "credential2",
                "format": "jwt_vp",
                "path": "$",
                "path_nested": {
                    "id": "credential2",
                    "format": "jwt_vc",
                    "path": "$.vp.verifiableCredential[0]"
                }
            }
        ]
    }"#;

    let data = credential_data_with_custom_pd(STATIC_VP_TOKEN, NONCE, pd, ps);
    let result = verify_oid4vp_offline(&data, VERIFIER_ID, VERIFIER_ID)
        .expect("Multi-descriptor PEX test should not error");

    assert_eq!(
        result.status,
        VerificationStatus::Valid,
        "Multi-descriptor PD with all constraints satisfied MUST be Valid; warnings: {:?}",
        result.warnings
    );
}

// ── §5  Result Shape Invariants ───────────────────────────────────────────────

/// `revocation_status` in the offline path must always be `Unknown` (no CRL
/// available offline).
#[test]
fn offline_revocation_status_is_unknown() {
    use serde_json::Value;
    let data = credential_data(STATIC_VP_TOKEN, NONCE);
    let result = verify_oid4vp_offline(&data, VERIFIER_ID, VERIFIER_ID).unwrap();
    // Serialize and check — RevocationStatus::Unknown serializes to "unknown"
    let json = serde_json::to_value(&result).unwrap();
    assert_eq!(
        json["revocation_status"],
        Value::String("unknown".to_string()),
        "Offline revocation_status must be 'unknown'"
    );
}

/// `verified_at` must be a valid RFC 3339 timestamp.
#[test]
fn offline_result_verified_at_is_rfc3339() {
    let data = credential_data(STATIC_VP_TOKEN, NONCE);
    let result = verify_oid4vp_offline(&data, VERIFIER_ID, VERIFIER_ID).unwrap();
    chrono::DateTime::parse_from_rfc3339(&result.verified_at)
        .expect("verified_at must be a valid RFC 3339 timestamp");
}

/// `emrtd_details`, `dtc_details`, and `open_badge_details` must always be
/// `None` for OID4VP verification results.
#[test]
fn offline_result_non_oid4vp_detail_fields_are_none() {
    let data = credential_data(STATIC_VP_TOKEN, NONCE);
    let result = verify_oid4vp_offline(&data, VERIFIER_ID, VERIFIER_ID).unwrap();
    assert!(result.emrtd_details.is_none());
    assert!(result.dtc_details.is_none());
    assert!(result.open_badge_details.is_none());
}
